import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';
const fixture = JSON.parse(readFileSync('.cache/social-fixture.json', 'utf8'));

test.beforeEach(async ({ request }) => {
  const headers = { Authorization: `Bearer ${fixture.reader.accessToken}` };
  const api = process.env.TEST_API ?? 'http://127.0.0.1:3000';
  expect((await request.post(`${api}/posts/${fixture.post.id}/like`, { headers, data: { liked: false } })).ok()).toBeTruthy();
  expect((await request.delete(`${api}/users/${fixture.author.user.id}/follow`, { headers })).ok()).toBeTruthy();
});

test('real API: like/follow persist through reload, back and hover; no React errors', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', e => { errors.push(e.message); console.log('BROWSER ERROR', e.message); });
  page.on('console', msg => {
    if (msg.type() === 'error') console.log('CONSOLE', msg.text().slice(0,1200));
    if (msg.type() === 'error' && /Maximum update|hydration|Hydration|snapshot|Cannot update/.test(msg.text())) errors.push(msg.text());
  });
  await page.goto('/en/login');
  await page.locator('input[type=email]').fill(fixture.reader.user.email);
  await page.locator('input[type=password]').fill(fixture.password);
  await page.locator('button[type=submit]').click();
  await expect(page).not.toHaveURL(/\/login/);
  await page.goto('/en/posts');
  const card = page.locator('article').filter({ hasText: fixture.post.title }).first();
  const heart = card.locator('button[data-liked]');
  await expect(heart).toBeEnabled();
  await expect(heart).toHaveAttribute('data-liked', 'false');
  await heart.click();
  await expect(heart).toHaveAttribute('data-liked', 'true');
  await expect(heart.locator('.num-en')).toHaveText('1');
  await page.reload();
  await expect(heart).toHaveAttribute('data-liked', 'true');
  await expect(heart.locator('.num-en')).toHaveText('1');
  await card.locator(`a[href="/en/posts/${fixture.post.slug}"]`).first().click();
  await expect(page).toHaveURL(new RegExp(fixture.post.slug));
  const detailHeart = page.locator('button[data-liked]').first();
  await expect(detailHeart).toHaveAttribute('data-liked', 'true');
  await expect(detailHeart.locator('.num-en')).toHaveText('1');
  const back = page.getByRole('button', { name: 'Back', exact: true });
  await expect(back).toHaveText('');
  await back.click();
  await expect(page).toHaveURL(/\/en\/posts$/);
  await expect(heart).toHaveAttribute('data-liked', 'true');
  await heart.click();
  await expect(heart).toHaveAttribute('data-liked', 'false');
  await expect(heart.locator('.num-en')).toHaveText('0');
  await page.reload();
  await expect(heart).toHaveAttribute('data-liked', 'false');
  await expect(heart.locator('.num-en')).toHaveText('0');
  // A profile reached from the list must return to that list, not home.
  await card.locator(`a[href="/en/users/${fixture.author.user.id}"]`).first().click();
  const follow = page.getByRole('button', { name: 'Follow', exact: true }).first();
  await expect(follow).toBeEnabled();
  await follow.hover();
  await expect(follow).toHaveText('Follow');
  await follow.click();
  const following = page.getByRole('button', { name: 'Unfollow', exact: true }).first();
  await expect(following).toHaveAttribute('aria-pressed', 'true');
  await following.hover();
  await expect(following.locator('span:visible')).toHaveText('Unfollow');
  await page.mouse.move(0, 0);
  await expect(following.locator('span:visible')).toHaveText('Following');
  await page.reload();
  await expect(following).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await expect(page).toHaveURL(/\/en\/posts$/);
  await card.locator(`a[href="/en/users/${fixture.author.user.id}"]`).first().click();
  await expect(following).toHaveAttribute('aria-pressed', 'true');
  await following.click();
  await expect(follow).toHaveAttribute('aria-pressed', 'false');
  await page.reload();
  await expect(follow).toHaveAttribute('aria-pressed', 'false');
  expect(errors).toEqual([]);
});

test('mobile RTL: optimistic rollback, refresh, and arrow returns to previous page', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  const fa = JSON.parse(readFileSync('messages/fa.json', 'utf8'));
  await page.goto('/fa/login');
  await page.locator('input[type=email]').fill(fixture.reader.user.email);
  await page.locator('input[type=password]').fill(fixture.password);
  await page.locator('button[type=submit]').click();
  await expect(page).not.toHaveURL(/\/login/);
  await page.goto('/fa/posts');
  const card = page.locator('article').filter({ hasText: fixture.post.title }).first();
  const heart = card.locator('button[data-liked]');
  await expect(heart).toBeEnabled();
  const zero = await heart.locator('.num-en').innerText();
  // Deliberate transport failure, not a replacement API. Confirm rollback.
  await page.route(`**/api/posts/${fixture.post.id}/like`, async route => {
    await new Promise(resolve => setTimeout(resolve, 400));
    await route.abort('failed');
  });
  await heart.click();
  await expect(heart).toHaveAttribute('data-liked', 'true');
  await expect(heart).toHaveAttribute('data-liked', 'false');
  await expect(heart.locator('.num-en')).toHaveText(zero);
  await page.unroute(`**/api/posts/${fixture.post.id}/like`);
  const saved = page.waitForResponse(r => r.url().endsWith(`/posts/${fixture.post.id}/like`) && r.request().method() === 'POST');
  await heart.click();
  expect((await saved).ok()).toBeTruthy();
  await expect(heart).toHaveAttribute('data-liked', 'true');
  const one = await heart.locator('.num-en').innerText();
  expect(one).not.toEqual(zero);
  await page.reload();
  await expect(heart).toHaveAttribute('data-liked', 'true');
  await expect(heart.locator('.num-en')).toHaveText(one);
  await card.locator(`a[href="/fa/users/${fixture.author.user.id}"]`).first().click();
  let follow = page.getByRole('button', { name: fa.profile.follow, exact: true }).first();
  await expect(follow).toBeEnabled();
  await page.route(`**/api/users/${fixture.author.user.id}/follow`, async route => {
    await new Promise(resolve => setTimeout(resolve, 400));
    await route.abort('failed');
  });
  await follow.click();
  await expect(page.getByRole('button', { name: fa.profile.unfollow, exact: true }).first()).toHaveAttribute('aria-pressed', 'true');
  await expect(follow).toHaveAttribute('aria-pressed', 'false');
  await page.unroute(`**/api/users/${fixture.author.user.id}/follow`);
  const followSaved = page.waitForResponse(r => r.url().endsWith(`/users/${fixture.author.user.id}/follow`) && r.request().method() === 'POST');
  await follow.click();
  expect((await followSaved).ok()).toBeTruthy();
  await page.reload();
  await expect(page.getByRole('button', { name: fa.profile.unfollow, exact: true }).first()).toHaveAttribute('aria-pressed', 'true');
  const back = page.getByRole('button', { name: fa.common.back, exact: true });
  await expect(back).toHaveText('');
  await back.click();
  await expect(page).toHaveURL(/\/fa\/posts$/);
  await expect(heart).toHaveAttribute('data-liked', 'true');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  expect(errors).toEqual([]);
});
